puts 'Welcome to OOP Class Design Lesson'
puts 'OOP is very basic important thing in development today, follow these rules will make your own OOP and design to next level'
puts 'This tutorial write in Ruby, but you can use for another language'
puts 'Idea of tutorial show by rhacker - in Ruby VietNam, I change them to program for easier to learn!'
puts 'Let go'

puts '======================================'
puts '5 Rule OOP Class Design'
puts '======================================'
puts '1. baby.rb'
puts '2. child.rb'
puts '3. teenager.rb'
puts '4. adult.rb'
puts '5. senior.rb'
puts '======================================'
puts 'Big note: not execute the code, because it only demo ;) '

